enable locking test fixture
os-brick 5.1 and later now uses file system locks
by default which were introduced by
I6f7f7d19540361204d4ae3ead2bd6dcddb8fcd68

As such we should be enabling the locking fixture
in the compute manager test class and block device
unit tests.

[Nectar] This will fix the unit test errors:
oslo_config.cfg.RequiredOptError: value required for option lock_path in group [DEFAULT]

Change-Id: I184ed3ad3d578780524fbaa3a0392607d1a50cdc
Related-Bug: #1947370
(cherry picked from commit 8dafea25e3c3986b01d6ef11e0b8ce35fb9206ae)