Add regression test for bug 1914777
This adds two tests to cover a regression where racing create and
delete requests could result in a user receiving a 500 error when
attempting to delete an instance:

  Unexpected exception in API method: AttributeError: 'NoneType' object
  has no attribute 'uuid'

Related-Bug: #1914777

NOTE(melwitt): The difference from the cherry picked change is because
I6daea47988181dfa6dde3d9c42004c0ecf6ae87a is not in Ussuri.

Change-Id: I8249c572c6f727ef4ca434843106b9b57c47e585
(cherry picked from commit f7975d640ce1e9fa06d045d35177f07451716f0c)
(cherry picked from commit 4f17ea2f7dedb67802c2a8bc0caa64ff66fd2c9c)